#! /bin/bash

source ~/.bashrc

fbsetbg -r ~/wallpapers/fractals/ || true
# /usr/lib/misc/xscreensaver/busyspheres --root&

xset -b            # Turn off beeps:
xset r rate 195 35 # Increase the keyboard repeat-rate:
#xrandr -s 1280x1024

xrdb -merge ~/.Xdefaults

# Your favourite mouse cursor:
# xsetroot -cursor_name right_ptr

xmodmap ~/.xmodmaprc

urxvtd -f &

#if which soulmebaby 2>/dev/null >/dev/null ; then
#   soulmebaby & disown
#fi

# if which psi 2>/dev/null >/dev/null ; then
#    psi & disown
# fi

# if [[ "$HOSTNAME" = "Vortex" ]] ; then
#     xchat & disown
#     thunderbird & disown
# fi

if [[ "${FLUXBOX_SVN}" = "TRUE" ]] ; then
    exec /home/babali/local/bin/fluxbox -log "/home/babali/.fluxbox/log"
else
    exec /usr/bin/fluxbox -log "/home/babali/.fluxbox/log"
fi
