# bashrc
# This file created by portage2paludis.bash
export CHOST="i686-pc-linux-gnu"
export CFLAGS="-O2 -pipe -march=athlon-xp -fomit-frame-pointer -fPIC"
export CXXFLAGS="${CFLAGS}"
export MAKEOPTS="-j2"
export SKIP_FUNCTIONS=test

