;; -*- mode: Lisp; -*-
(defconst epita-c-style
  '((c-tab-always-indent . t)
    (c-comment-only-line-offset . 0)
    (c-hanging-braces-alist . ((substatement-open after)
                               (brace-list-open)))
    (c-hanging-colons-alist . ((member-init-intro before)
                               (inher-intro)
                               (case-label after)
                               (label 0)
                               (access-label after)))
    (c-cleanup-list . (scope-operator empty-defun-braces defun-close-semi))
    (c-basic-offset . 2)
    (c-offsets-alist . ((substatement . +)
			(substatement-open . 0)
                        (case-label . 0)
                        (statement-case-open . 0)
                        (block-open . 0)
                        (brace-list-open . 0)
                        (inline-open . 0)
                        (statement-block-intro . +)
                        ))
    (c-echo-syntactic-information-p . t))
  "Epita Programming Style")
(c-add-style "epita" epita-c-style)
