;; Create my personal style.
(defconst kaneton-c-style
  '((c-tab-always-indent . t)
    (c-comment-only-line-offset . 0)
    (c-hanging-braces-alist . ((substatement-open after)
                               (brace-list-open)))
    (c-hanging-colons-alist . ((member-init-intro before)
                               (inher-intro)
                               (case-label after)
                               (label after)
                               (access-label after)))
    (c-cleanup-list . (scope-operator empty-defun-braces defun-close-semi))
    (c-basic-offset . 3)
    (c-offsets-alist . ((substatement . 3)
			(substatement-open . 0)
                        (case-label . 0)
                        (statement-case-open . 0)
                        (block-open . 3)
                        (brace-list-open . 0)
                        (statement-block-intro 3)
                        ))
    (c-echo-syntactic-information-p . t))
  "Kaneton Programming Style")
(c-add-style "kaneton" kaneton-c-style)

;; (setq c-default-style "kaneton")
