;; -*- mode: Lisp; -*-
;; Style for qemu
(defconst qemu-c-style
  '((c-tab-always-indent . t)
    (c-comment-only-line-offset . 0)
    (c-hanging-braces-alist . ((substatement-open after)
                               (brace-list-open)))
    (c-hanging-colons-alist . ((member-init-intro before)
                               (inher-intro)
                               (case-label after)
                               (label after)
                               (access-label after)))
    (c-cleanup-list . (scope-operator empty-defun-braces defun-close-semi))
    (c-basic-offset . 4)
    (c-offsets-alist . ((substatement . 4)
			(substatement-open . 0)
                        (case-label . 0)
                        (statement-case-open . 0)
                        (block-open . 4)
                        (brace-list-open . 0)
                        (statement-block-intro 4)
                        ))
    (c-echo-syntactic-information-p . t))
  "QEMU Programming Style")
(c-add-style "qemu" qemu-c-style)
