(defconst epita-c-style
  '((c-tab-always-indent . t)
    (c-comment-only-line-offset . 0)
    (c-hanging-braces-alist . ((substatement-open after)
                               (brace-list-open)))
    (c-hanging-colons-alist . ((member-init-intro before)
                               (inher-intro)
                               (case-label after)
                               (label 0)
                               (access-label after)))
    (c-cleanup-list . (scope-operator empty-defun-braces defun-close-semi))
    (c-basic-offset . 4)
    (c-offsets-alist . ((substatement . +)
			(substatement-open . 0)
                        (case-label . 0)
                        (statement-case-open . 0)
                        (block-open . 0)
                        (brace-list-open . 0)
                        (inline-open . 0)
                        (statement-block-intro . +)
                        (statement-case-open . +)
                        ))
    (c-echo-syntactic-information-p . t))
  "U-HE Programming Style")
(c-add-style "u-he" epita-c-style)

(defun u-he-style ()
  (interactive)

  (setq indent-tabs-mode 0)
  (setq tab-width 4)

  (when (memq major-mode '(sh-mode))
	(setq tab-width 8)
	(setq indent-tabs-mode 0)
    (setq sh-basic-offset 4)
    )

  (when (memq major-mode '(python-mode))
    (setq indent-tabs-mode nil)
    (when (equal (point-min) (point-max))
      (freebox-generate-python-header))
    )

  (when (memq major-mode '(c-mode c++-mode))
    (c-set-style "u-he")

	(when (and (string-match ".*\\.hh?" buffer-file-name)
               (equal (point-min) (point-max)))
      (freebox-generate-c-header))
  )
)
